//*********************************************************
//
// Copyright (c) Microsoft. All rights reserved.
// This code is licensed under the MIT License (MIT).
// THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
// IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
// PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
//
//*********************************************************

// FrameProviderSampleMft0.idl : IDL source for MFT0
//

// This file will be processed by the MIDL tool to
// produce the type library (FrameProviderSampleMft0.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "Inspectable.idl";
import "mftransform.idl";
[
    object,
    uuid(805222A9-54D6-4D89-B581-CB074097FE01),
    oleautomation,
    nonextensible,
    pointer_default(unique)
]
interface IFrameProviderMft0 : IUnknown{

};
[
    uuid(6BD93230-BACB-4421-87CD-CC7A7816ED4A),
    version(1.0),
]
library FrameProviderSampleMft0Lib
{
    importlib("stdole2.tlb");
    [
        uuid(DDBE4BC1-541F-4D43-A25B-1F23E7AF4505)
    ]
    coclass FrameProviderMft0
    {
        [default] interface IFrameProviderMft0;
        interface IInspectable;
        interface IMFTransform;
    };
};

